name: unittest

on:
  push:
    # temporary disable unitest on all branches
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Install uv
          uses: astral-sh/setup-uv@v3

        - name: Install project build system requirements (ninja)
          run: sudo apt-get update && sudo apt-get install -y ninja-build

        - name: Set up Python ${{ matrix.python-version }}
          run: uv python install ${{ matrix.python-version }}

        - name: Run tests
          run: |
            uv run pytest --junitxml=pytest.xml -m 'not slow and not aicam' | tee pytest-coverage.txt

        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always() && github.event_name != 'pull_request'
          with:
            comment_mode: off
            files: |
              ./pytest.xml
          
        - name: Pytest coverage comment
          uses: MishaKav/pytest-coverage-comment@main
          if: always() && github.event_name == 'pull_request'
          with:
            pytest-coverage-path: ./pytest-coverage.txt
            junitxml-path: ./pytest.xml